# Generated by Django 2.2.14 on 2020-11-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achieve', '0002_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
