# Generated by Django 2.2.14 on 2020-11-08 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achieve', '0003_task_remarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='remarks',
            new_name='description',
        ),
    ]
