# Generated by Django 3.1.1 on 2020-11-17 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achieve', '0004_auto_20201108_1201'),
        ('achieve', '0002_kin'),
    ]

    operations = [
    ]
