# Generated by Django 3.1.1 on 2020-12-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achieve', '0005_merge_20201117_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Home', 'Home'), ('Work', 'Work'), ('School', 'School')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
