# Generated by Django 3.1.1 on 2021-02-04 01:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('achieve', '0010_auto_20210204_1042'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enduser',
            new_name='Kin',
        ),
    ]
