# Generated by Django 3.1.1 on 2021-02-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achieve', '0011_auto_20210204_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='kin',
            name='family_role',
            field=models.CharField(blank=True, choices=[('Father', 'Father'), ('Step Father', 'Step Father'), ('Mother', 'Mother'), ('Step Mother', 'Step Mother'), ('Brother', 'Brother'), ('Step Brother', 'Step Brother'), ('Sister', 'Sister'), ('Step Sister', 'Step Sister')], max_length=200, null=True),
        ),
    ]
