# Generated by Django 3.1.1 on 2021-02-07 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('achieve', '0012_kin_family_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Home', 'Home'), ('Work', 'Work'), ('School', 'School')], max_length=200),
        ),
        migrations.AlterField(
            model_name='kin',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='kin',
            name='family_role',
            field=models.CharField(choices=[('Father', 'Father'), ('Step Father', 'Step Father'), ('Mother', 'Mother'), ('Step Mother', 'Step Mother'), ('Brother', 'Brother'), ('Step Brother', 'Step Brother'), ('Sister', 'Sister'), ('Step Sister', 'Step Sister')], max_length=200),
        ),
        migrations.AlterField(
            model_name='kin',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='kin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
